name: eventsubscriber
version: 2.1.2
description: A Flutter widget that updates (rebuilds) when an Event occurs.
homepage: https://github.com/aryehof/dart-eventsubscriber

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  event: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.16.5
  lints: ^1.0.0
