name: eventsubscriber
version: 1.1.0
description: A Flutter widget that supports subscribing to an [Event].
homepage: https://github.com/aryehof/dart-eventsubscriber

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  event: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  test: ^1.6.0
