name: eventsubscriber
version: 3.0.0
description: A Flutter widget that updates (rebuilds) when an Event occurs.
homepage: https://github.com/aryehof/dart-eventsubscriber

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  event: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^4.0.0
  test: ^1.25.0
